---
title: "Summary of Contributions"
---

## Journals 
- [AKRON: An Algorithm for Approximating Sparse Kernel Reconstruction](http://www.sciencedirect.com/science/article/pii/S0165168417303791)<br />
  G. Ditzler, N. Bouaynaya, and R. Shterenberg <br />
  Signal Processing, 2017. To appear.
- [Improvements to Scalable Online Feature Selection Using Bagging and Boosting](http://ieeexplore.ieee.org/document/8065078/)<br />
  G. Ditzler, J. LaBarck, J. Ritchie, G. Rosen, and R. Polikar<br />
  IEEE Transactions on Neural Networks and Learning Systems, 2017. To appear.
- [A Sequential Learning Approach for Scaling up Filter-Based Feature Subset Selection](http://ieeexplore.ieee.org/abstract/document/7926436/)<br />
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Neural Networks and Learning Systems, 2017. (accepted)
- [Fizzy: Feature selection for metagenomics](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0793-8)<br />
  G. Ditzler, J. Calvin Morrison, Y. Lan, and G. Rosen<br />
  BMC Bioinformatics, 2015, vol 16, no. 358. [code]
- [Multi-Layer and Recursive Neural Networks for Metagenomic Classification](http://ieeexplore.ieee.org/document/7219432/)<br />
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Nanobioscience, 2015, vol. 14, no. 6, pp. 608-616.
- [Adaptive strategies for learning in nonstationary environments: a survey](http://ieeexplore.ieee.org/document/7296710/)<br />
  G. Ditzler, M. Roveri, C. Alippi, and R. Polikar<br />
  IEEE Computational Intelligence Magazine, 2015, vol. 10, no. 4, pp. 12-25.  
- [A bootstrap based Neyman-Pearson test for identifying variable importance](http://ieeexplore.ieee.org/document/6823119/)<br />
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Neural Networks and Learning Systems, 2015, vol. 26, no. 4, pp. 880-886. 
- [Incremental learning of concept drift from streaming imbalanced data](http://ieeexplore.ieee.org/document/6235959/)<br />
  G. Ditzler and R. Polikar<br />
  IEEE Transactions on Knowledge & Data Engineering, 2013, vol. 25, no. 10, pp. 2283–2301.
 

## Conferences 

- [Fine Tuning Lasso in an Adversarial Environment Against Gradient Attacks](http://www.ele.uri.edu/ieee-ssci2017/) <br />
  G. Ditzler and A. Prater <br />
  IEEE Symposium Series on Computational Intelligence, 2017.
- [Speeding Up Joint Mutual Information Feature Selection with an Optimization Heuristic](http://www.ele.uri.edu/ieee-ssci2017/) <br />
  H. Liu and G. Ditzler <br />
  IEEE Symposium Series on Computational Intelligence, 2017.
- [Framework to Support DDDAS Decision” Support Systems: Design Overview](http://ieeexplore.ieee.org/abstract/document/8064150/) <br />
  G. Ditzler, A. Akoglu, and S. Hariri <br />
  Workshop on InfoSymbiotics: DDDAS Dynamic Data Driven Applications Systems, 2017.
- [A Self-Protection Agent using Error Correcting Output Codes to Secure Computers and Applications](http://ieeexplore.ieee.org/abstract/document/8064054/)  <br />
  F. de la Pena Montero, S. Hariri, and G. Ditzler <br />
  IEEE International Conference on Cloud and Autonomic Computing, 2017.
- [Autonomic Management of 3D Cardiac Simulations](http://ieeexplore.ieee.org/abstract/document/8064049/) <br />
  E. Esmaili, A. Akoglu, G. Ditzler, S. Hariri, J. Szep and T. Moukabary <br />
  IEEE International Conference on Cloud and Autonomic Computing, 2017. (best paper award)
- [Fraud Analysis Approaches in the Age of Big Data - A Review of State of the Art](http://ieeexplore.ieee.org/abstract/document/8064067/) <br />
  S. Makki, R. Haque, Y. Taher, Z. Assaghir, G. Ditzler, M.-S. Hacid and H. Zeineddine <br />
  International Workshop on Autonomic Systems for Big Data Analytics, 2017.
- [A Fast Information-theoretic Approximation of Joint Mutual Information Feature Selection](http://ieeexplore.ieee.org/abstract/document/7966441/?reload=true) <br />
  H. Liu and G. Ditzler <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2017.
- [The AKRON-Kalman Filter for Tracking Time-Varying Networks](http://ieeexplore.ieee.org/abstract/document/7897268/) <br />
  V. Carluccio, N. Bouaynaya, G. Ditzler, and H. M. Fathallah Shaykh <br />
  IEEE International Conference on Biomedical and Health Informatics, 2017.
- [A Study of Incremental Spectral Meta-Learning for Nonstationary Environments](http://ieeexplore.ieee.org/abstract/document/7727178/) <br />
  G. Ditzler   <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2016.
- [Scaling a Neyman-Pearson subset selection approach via heuristics for mining massive data ](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=7008701)<br />
  G. Ditzler, M. Austen, R, Polikar, and G. Rosen <br />
  IEEE Symposium on Computational Intelligence in Data Mining, 2014. (travel award) 
- [Feature Subset Selection for Inferring Relative Importance of Taxonomy](http://dl.acm.org/citation.cfm?id=2660824) <br />
  G. Ditzler and G. Rosen <br />
  ACM International Workshop on Big Data in Life Sciences, 2014. (invited and travel award)
- [Domain Adaptation Bounds for Multiple Expert Systems Under Concept Drift](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6889909) <br />
  G. Ditzler, G. Rosen, and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2014. (travel award & best student paper) 
- [Incremental learning of new classes with unbalanced data](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6706770) <br />
  G. Ditzler, G. Rosen, and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2013.
- [Discounted expert weighting for concept drift](http://ieeexplore.ieee.org/document/6595773/?arnumber=6595773) <br />
  G. Ditzler, G. Rosen and R. Polikar <br />
  IEEE International Symposium on Computational Intelligence in Dynamic and Uncertain Environments, 2013.
- [Information theoretic feature selection for high dimensional metagenomic data](http://ieeexplore.ieee.org/document/6507749/?arnumber=6507749) <br />
  G. Ditzler, R. Polikar, and G. Rosen <br />
  IEEE International Workshop on Genomic Signal Processing and Statistics, 2012.
- [A transductive learning algorithm for concept drift](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6252494) <br />
  G. Ditzler, G. Rosen and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2012.
- [Determining significance in metagenomics](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6207004) <br />
  G. Ditzler, R. Polikar and G. Rosen <br />
  IEEE North Eastern Biomedical Engineering Conference, 2012.
- [Forensic identification with environmental samples](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6288265) <br />
  G. Ditzler, R. Polikar, and G. Rosen   <br />
  IEEE International Conference on Acoustic, Speech and Signal Processing, 2012.
- [Semi-supervised learning in nonstationary environments](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6033578) <br />
  G. Ditzler and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2011. (student travel award)
- [Hellinger distance based drift detection algorithm](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5948491) <br />
  G. Ditzler and R. Polikar  <br />
  IEEE Symposium on Computational Intelligence in Dynamic and Uncertain Environments, 2011.
- [Fusion methods for boosting performance of speaker identification systems](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5774964) <br />
  G. Ditzler, J. Ethridge, R. Polikar, and R. Ramachandran <br />
  Asia Pacific Conference of Circuits and Systems, 2010.
- [An incremental learning algorithm for nonstationary environments and imbalanced data](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5597278) <br />
  G. Ditzler, R. Polikar, and N. V. Chawla <br />
  International Conference on Pattern Recognition, 2010.
- [Optimal $\nu$-SVM parameter estimation using multi-objective evolutionary algorithms](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5586029) <br />
  J. Ethridge, G. Ditzler, and R. Polikar <br />
  IEEE Congress on Evolutionary Computing, 2010.
- [An ensemble-based incremental learning framework for concept drift and class imbalance](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5596764) <br />
  G. Ditzler and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2010.
- [Incremental learning of new classes in unbalanced data: Learn++.UDNC](https://link.springer.com/chapter/10.1007/978-3-642-12127-2_4) <br />
  G. Ditzler, M. Muhlbaier, and R. Polikar <br />
  International Workshop on Multiple Classifier Systems, 2010.
